import './globals.css'

export const metadata = {
  title: 'NAST Next.js Starter',
  description: 'Generated by NAST Next.js Starter',
}

import { Inter } from 'next/font/google'

const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  className={`${inter.variable}`}>
      <body>{children}</body>
    </html>
  )
}
